server:
  port: 8762   #端口号
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:   #注册中心地址
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: fsd-common   #在注册中心显示的名字

